AGACEApp/FIS-PortalEmpleadoOrdenes/src/main/java/mx/gob/sat/siat/feagace/vista/ordenes/cifras/CifrasConsultaManagedBean.java
package mx.gob.sat.siat.feagace.vista.ordenes.cifras;

import java.io.IOException;
import java.math.BigDecimal;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import org.primefaces.component.accordionpanel.AccordionPanel;
import org.primefaces.event.SelectEvent;
import org.primefaces.event.TabChangeEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import mx.gob.sat.siat.feagace.modelo.dto.ordenes.AgaceOrden;
import mx.gob.sat.siat.feagace.vista.ordenes.cifras.helper.CifrasAttributeHelper;
import mx.gob.sat.siat.feagace.vista.ordenes.cifras.helper.CifrasColumasDetalleHelper;
import mx.gob.sat.siat.feagace.vista.ordenes.documentacion.managedbean.DocumentacionFirmanteMB;

@ManagedBean(name = "cifrasConsultaManagedBean")
@ViewScoped
public class CifrasConsultaManagedBean extends CifrasManagedBean {

    private static final long serialVersionUID = 1L;

    private boolean vieneDetalleOrdenUnif;

    @ManagedProperty(value = "#{documentacionFirmanteMB}")
    private DocumentacionFirmanteMB documentacionFirmanteMB;

    private boolean reporteVisible;

    @PostConstruct
    public void init() {

        if (getSession().getAttribute("ordenSeleccionadaC") != null) {
            getDocumentacionFirmanteMB().setOrdenSeleccionado((AgaceOrden) getSession().getAttribute("ordenSeleccionadaC"));
            setVieneDetalleOrdenUnif(true);
            getSession().removeAttribute("ordenSeleccionadaC");
        }
        setColumnaDetalleHelper(new CifrasColumasDetalleHelper());
        BigDecimal idOrden = documentacionFirmanteMB.getOrdenSeleccionado().getId();
        setTotalCifras(getCifrasService().obtenerEncabezadoCifras(idOrden));
        setCifrasAttributeHelper(new CifrasAttributeHelper());
        obtenerTotalEncabezado();
        reporteVisible();
    }

    public void reporteVisible() {
        if (getListaEncabezadoCifras() != null
                && !getListaEncabezadoCifras().isEmpty()) {
            setReporteVisible(false);
        } else {
            setReporteVisible(true);
        }
    }

    public void obtenerHistoricoEncabezado() {
        BigDecimal idOrden = documentacionFirmanteMB.getOrdenSeleccionado().getId();
        obtenerHistoricoEncabezado(idOrden);
    }

    public void mostrarDetalleHistorico() {
        BigDecimal idOrden = documentacionFirmanteMB.getOrdenSeleccionado().getId();
        mostrarDetalleHistorico(idOrden);
    }

    public void onRowSelect(SelectEvent event) {
        BigDecimal idOrden = documentacionFirmanteMB.getOrdenSeleccionado().getId();
        setImpuestosSeleccionados(
                getCifrasService().obtenerCifrasPorOrdenCifraTipoCifra(idOrden, getEncabezadoCifraSeleccionada().getTipoCifra().getIdCifra()));
        if (getImpuestosSeleccionados() != null && !getImpuestosSeleccionados().isEmpty()) {
            getCifrasAttributeHelper().setTablaImpuestosVisible(true);
        }
    }

    public void onTabChange(TabChangeEvent event) {
        String indiceActivo = ((AccordionPanel) event.getComponent()).getActiveIndex();
        BigDecimal idOrden = documentacionFirmanteMB.getOrdenSeleccionado().getId();
        int tipoCifra = Integer.parseInt(indiceActivo) + 1;
        configurarPantalla(tipoCifra);
        obtenerListaCifras(idOrden, new BigDecimal(tipoCifra));
        getCifrasAttributeHelper().setTablaImpuestosVisible(false);
        setTabSeleccionado(tipoCifra);
        reporteVisible();
    }

    public void redireccionaRegreso() throws IOException {

        String urlRedireccion = "/faces/consultarDocumentos/detalleOrdenDocUnificado.jsf";

        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        HttpServletRequest origRequest = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();

        externalContext.redirect(origRequest.getContextPath() + urlRedireccion);

    }

    public StreamedContent getArchivoExcel() {
        BigDecimal idOrden = documentacionFirmanteMB.getOrdenSeleccionado().getId();
        DefaultStreamedContent excel = null;
        try {
            excel = new DefaultStreamedContent(getCifrasService().getReporteConsulta(idOrden, new BigDecimal(getTabSeleccionado())),
                    "application/vnd.ms-excel", "reporte_cifras.xls");
        } catch (Exception e) {
            logger.error("error en xls ", e);
        }
        return excel;
    }

    public DocumentacionFirmanteMB getDocumentacionFirmanteMB() {
        return documentacionFirmanteMB;
    }

    public void setDocumentacionFirmanteMB(DocumentacionFirmanteMB documentacionFirmanteMB) {
        this.documentacionFirmanteMB = documentacionFirmanteMB;
    }

    public boolean isVieneDetalleOrdenUnif() {
        return vieneDetalleOrdenUnif;
    }

    public void setVieneDetalleOrdenUnif(boolean vieneDetalleOrdenUnif) {
        this.vieneDetalleOrdenUnif = vieneDetalleOrdenUnif;
    }

    public boolean isReporteVisible() {
        return reporteVisible;
    }

    public void setReporteVisible(boolean reporteVisible) {
        this.reporteVisible = reporteVisible;
    }

}

AGACEApp/FIS-PortalEmpleadoOrdenes/src/main/java/mx/gob/sat/siat/feagace/vista/ordenes/cifras/CifrasManagedBean.java
package mx.gob.sat.siat.feagace.vista.ordenes.cifras;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedProperty;

import org.primefaces.model.StreamedContent;

import mx.gob.sat.siat.feagace.modelo.dto.ordenes.FeceaCifraImpuestoDTO;
import mx.gob.sat.siat.feagace.modelo.dto.ordenes.FecetCifraDTO;
import mx.gob.sat.siat.feagace.modelo.dto.ordenes.FecetParcialidadCifraDTO;
import mx.gob.sat.siat.feagace.modelo.dto.ordenes.TotalCifrasDTO;
import mx.gob.sat.siat.feagace.modelo.util.Constantes;
import mx.gob.sat.siat.feagace.negocio.ordenes.cifras.service.CifrasService;
import mx.gob.sat.siat.feagace.vista.common.AbstractManagedBean;
import mx.gob.sat.siat.feagace.vista.ordenes.cifras.helper.CifrasAttributeHelper;
import mx.gob.sat.siat.feagace.vista.ordenes.cifras.helper.CifrasColumasDetalleHelper;

public class CifrasManagedBean extends AbstractManagedBean {

    private static final long serialVersionUID = 1L;

    public static final BigDecimal SINOPCION = new BigDecimal(-1);
    private static final int NUM_1 = 1;
    private static final int NUM_2 = 2;
    private static final int NUM_3 = 3;

    @ManagedProperty(value = "#{cifrasService}")
    private transient CifrasService cifrasService;

    private transient CifrasAttributeHelper cifrasAttributeHelper;

    private transient CifrasColumasDetalleHelper columnaDetalleHelper;

    private List<TotalCifrasDTO> totalCifras;

    private List<FecetCifraDTO> listaEncabezadoCifras;

    private List<FecetCifraDTO> listaEncabezadoCifrasHistorico;

    private FecetCifraDTO encabezadoCifraSeleccionada;

    private FecetCifraDTO encabezadoCifraHistoricoSeleccionada;

    private BigDecimal totalEncabezado;

    private BigDecimal totalMontoCifras;

    private List<FeceaCifraImpuestoDTO> impuestosSeleccionados;

    private FeceaCifraImpuestoDTO impuestoSeleccionado;

    private List<FeceaCifraImpuestoDTO> impuestosDetalle;
    
    private int tabSeleccionado;

    public void configurarPantalla(int tipoPantalla) {
        switch (tipoPantalla) {
        case NUM_1:
            setValoresPantalla(true, false, false);
            break;
        case NUM_2:
            setValoresPantalla(false, true, false);
            break;
        case NUM_3:
            setValoresPantalla(false, false, true);
            break;
        default:
            setValoresPantalla(false, false, false);
            break;
        }
    }

    public void setValoresPantalla(boolean cobradas, boolean virtuales, boolean liquidadas) {
        getCifrasAttributeHelper().setPanelCifrasCobradasVisible(cobradas);
        getCifrasAttributeHelper().setPanelCifrasVirtualesVisible(virtuales);
        getCifrasAttributeHelper().setPanelCifrasLiquidadasVisible(liquidadas);
    }

    public void configurarDetalle(int tipoCifra) {
        switch (tipoCifra) {
        case NUM_1:
            setValoresDetalle(true, true, true, true, true);
            break;
        case NUM_2:
            setValoresDetalle(false, false, false, false, false);
            break;
        case NUM_3:
            setValoresDetalle(true, true, true, true, false);
            break;
        default:
            break;
        }
    }

    public void setValoresDetalle(boolean actualizacionesVisible, boolean multasVisible, boolean recargosVisible, boolean totalVisible,
            boolean parcialidadVisible) {
        getColumnaDetalleHelper().setActualizacionesVisible(actualizacionesVisible);
        getColumnaDetalleHelper().setMultasVisible(multasVisible);
        getColumnaDetalleHelper().setParcialidadVisible(parcialidadVisible);
        getColumnaDetalleHelper().setRecargosVisible(recargosVisible);
        getColumnaDetalleHelper().setTotalVisible(totalVisible);
    }

    public void mostrarDetalle() {
        if (getImpuestoSeleccionado().getParcialidad() == null) {
            getImpuestoSeleccionado().setParcialidad(new FecetParcialidadCifraDTO());
        }
        setImpuestosDetalle(new ArrayList<FeceaCifraImpuestoDTO>());
        getImpuestosDetalle().add(getImpuestoSeleccionado());
        configurarDetalle(getTabSeleccionado());
    }

    public void mostrarDetalleHistorico(BigDecimal idOrden) {
        setImpuestosDetalle(getCifrasService().obtenerImpuestosCifrasHistorico(idOrden, getEncabezadoCifraHistoricoSeleccionada().getTipoCifra().getIdCifra(),
                getEncabezadoCifraHistoricoSeleccionada().getConsecutivo()));
        configurarDetalle(getTabSeleccionado());
    }

    public void obtenerListaCifras(BigDecimal idOrden, BigDecimal tipoCifra) {
        BigDecimal montoTotal = Constantes.BIG_DECIMAL_CERO;
        setListaEncabezadoCifras(cifrasService.obtenerCifrasPorOrden(idOrden, tipoCifra));
        for (FecetCifraDTO cifra : getListaEncabezadoCifras()) {
            montoTotal = montoTotal.add(cifra.getTotal());
        }
        setTotalMontoCifras(montoTotal);
    }

    public void obtenerTotalEncabezado() {
        BigDecimal sumatoria = Constantes.BIG_DECIMAL_CERO;
        for (TotalCifrasDTO total : getTotalCifras()) {
            sumatoria = sumatoria.add(total.getMontoCifra());
        }
        setTotalEncabezado(sumatoria);
    }

    public void obtenerHistoricoEncabezado(BigDecimal idOrden) {
        setListaEncabezadoCifrasHistorico(getCifrasService().obtenerEncabezadoCifrasHistorico(getEncabezadoCifraSeleccionada().getIdCifra(), idOrden));
    }

    public CifrasAttributeHelper getCifrasAttributeHelper() {
        return cifrasAttributeHelper;
    }

    public void actualizaTotales() {
        setTotalMontoCifras(BigDecimal.ZERO);
        for (FecetCifraDTO cifra : getListaEncabezadoCifras()) {
            BigDecimal totalCifra = BigDecimal.ZERO;
            for (FeceaCifraImpuestoDTO cifraImpuesto : cifra.getCifras()) {
                totalCifra = totalCifra.add(cifraImpuesto.getTotal());
            }
            cifra.setTotal(totalCifra);
            setTotalMontoCifras(getTotalMontoCifras().add(cifra.getTotal()));
        }
    }

    public void setCifrasAttributeHelper(CifrasAttributeHelper cifrasAttributeHelper) {
        this.cifrasAttributeHelper = cifrasAttributeHelper;
    }

    public CifrasService getCifrasService() {
        return cifrasService;
    }

    public void setCifrasService(CifrasService cifrasService) {
        this.cifrasService = cifrasService;
    }

    public List<TotalCifrasDTO> getTotalCifras() {
        return totalCifras;
    }

    public void setTotalCifras(List<TotalCifrasDTO> totalCifras) {
        this.totalCifras = totalCifras;
    }

    public List<FecetCifraDTO> getListaEncabezadoCifras() {
        return listaEncabezadoCifras;
    }

    public void setListaEncabezadoCifras(List<FecetCifraDTO> listaEncabezadoCifras) {
        this.listaEncabezadoCifras = listaEncabezadoCifras;
    }

    public FecetCifraDTO getEncabezadoCifraSeleccionada() {
        return encabezadoCifraSeleccionada;
    }

    public void setEncabezadoCifraSeleccionada(FecetCifraDTO encabezadoCifraSeleccionada) {
        this.encabezadoCifraSeleccionada = encabezadoCifraSeleccionada;
    }

    public BigDecimal getTotalEncabezado() {
        return totalEncabezado;
    }

    public void setTotalEncabezado(BigDecimal totalEncabezado) {
        this.totalEncabezado = totalEncabezado;
    }

    public BigDecimal getTotalMontoCifras() {
        return totalMontoCifras;
    }

    public void setTotalMontoCifras(BigDecimal totalMontoCifras) {
        this.totalMontoCifras = totalMontoCifras;
    }

    public List<FeceaCifraImpuestoDTO> getImpuestosSeleccionados() {
        return impuestosSeleccionados;
    }

    public void setImpuestosSeleccionados(List<FeceaCifraImpuestoDTO> impuestosSeleccionados) {
        this.impuestosSeleccionados = impuestosSeleccionados;
    }

    public FeceaCifraImpuestoDTO getImpuestoSeleccionado() {
        return impuestoSeleccionado;
    }

    public void setImpuestoSeleccionado(FeceaCifraImpuestoDTO impuestoSeleccionado) {
        this.impuestoSeleccionado = impuestoSeleccionado;
    }

    public CifrasColumasDetalleHelper getColumnaDetalleHelper() {
        return columnaDetalleHelper;
    }

    public void setColumnaDetalleHelper(CifrasColumasDetalleHelper columnaDetalleHelper) {
        this.columnaDetalleHelper = columnaDetalleHelper;
    }

    public List<FeceaCifraImpuestoDTO> getImpuestosDetalle() {
        return impuestosDetalle;
    }

    public void setImpuestosDetalle(List<FeceaCifraImpuestoDTO> impuestosDetalle) {
        this.impuestosDetalle = impuestosDetalle;
    }

    public List<FecetCifraDTO> getListaEncabezadoCifrasHistorico() {
        return listaEncabezadoCifrasHistorico;
    }

    public void setListaEncabezadoCifrasHistorico(List<FecetCifraDTO> listaEncabezadoCifrasHistorico) {
        this.listaEncabezadoCifrasHistorico = listaEncabezadoCifrasHistorico;
    }

    public FecetCifraDTO getEncabezadoCifraHistoricoSeleccionada() {
        return encabezadoCifraHistoricoSeleccionada;
    }

    public void setEncabezadoCifraHistoricoSeleccionada(FecetCifraDTO encabezadoCifraHistoricoSeleccionada) {
        this.encabezadoCifraHistoricoSeleccionada = encabezadoCifraHistoricoSeleccionada;
    }
    
    public StreamedContent getArchivoPromocionDescarga() {
        getCifrasAttributeHelper().setArchivoDescarga(
                getDescargaArchivo(getCifrasAttributeHelper().getDocumentoSeleccionado().getRutaArchivo(),
                getCifrasAttributeHelper().getDocumentoSeleccionado().getNombre()));
        return getCifrasAttributeHelper().getArchivoDescarga();
    }
    
    public int getTabSeleccionado() {
        return tabSeleccionado;
    }

    public void setTabSeleccionado(int tabSeleccionado) {
        this.tabSeleccionado = tabSeleccionado;
    }

}

AGACEApp/FIS-PortalEmpleadoOrdenes/src/main/webapp/firmante/cifras/cifrasCobradas.xhtml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<f:view xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html">
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:p="http://primefaces.org/ui">       
           <p:panel styleClass="panel-interno" style="width:100% !important;" id="panelPrincipal">           
           <p:panelGrid id="panelResumen" style="width:100% !important;" styleClass="noBorders">
           <p:row>
           		<p:column>
           			 <p:dataTable id="tablaCifras"
                                    value="#{cifrasConsultaManagedBean.listaEncabezadoCifras}" 
                                    var="cifra"
                                    editable="false" emptyMessage="#{msj['label.lista.vacia']}"
                                    selection="#{cifrasConsultaManagedBean.encabezadoCifraSeleccionada}" rowKey="#{cifra}">       
                           <p:ajax event="rowSelectRadio" listener="#{cifrasConsultaManagedBean.onRowSelect}" 
                           			update=":formCifras:acordeonCifras:panelImpuestos" process="@this"/>                                                       
                           <f:facet name="header">
                           	<h:outputText value="#{msj['label.cifras.resumen.titulo']}"/>
                           </f:facet>   
                           <p:column selectionMode="single" style="text-align:center"/>
                           <p:column headerText="#{msj['titulo.cifras.tabla.resumen.cifras']}" width="35%" >
                           		<h:outputText value="#{cifra.tipoCifra.descripcion}"/>
                           </p:column>
                           <p:column headerText="#{msj['titulo.cifras.tabla.resumen.historico']}" width="10%">
                               <p:commandLink value="#{msj['btn.historico']}" style="color:blue;" oncomplete="PF('cifraHistoricoPanelWidget').show();"
                               		process="@this" action="#{cifrasConsultaManagedBean.obtenerHistoricoEncabezado}" update=":formCifras:tablaCifrasHistorico">
                               		<f:setPropertyActionListener value="#{cifra}"
                                       	target="#{cifrasConsultaManagedBean.encabezadoCifraSeleccionada}"/>
                               </p:commandLink>                           
                           </p:column>
                           <p:column headerText="#{msj['titulo.cifras.tabla.resumen.total']}" width="20%" styleClass="panel-principal"
                           	 style="text-align:right">
                               $<h:outputText value="#{cifra.total}">
                               		<f:convertNumber pattern="###,###,###,##0.00" locale="es_MX"/>
                               </h:outputText>
                           </p:column> 
                           <p:columnGroup type="footer">
				               <p:row>
						            <p:column style="text-align:right" footerText="Cifras Totales:"
						            	colspan="3"/>
						            <p:column style="text-align:right">
						            	<f:facet name="footer">	
							                $<h:outputText value="#{cifrasConsultaManagedBean.totalMontoCifras}" >
							                    <f:convertNumber pattern="###,###,###,##0.00" locale="es_MX"/>
							                </h:outputText>
							            </f:facet>
						            </p:column>
					            </p:row>
				            </p:columnGroup>                                      
                        </p:dataTable>
                </p:column>
                                
           	</p:row>
           	<p:row>
           		<p:column>
           			 <p:panel id="panelImpuestos" style="width:100% !important;border-style: none !important">
           			 <p:dataTable id="tablaImpuestos"
                                    value="#{cifrasConsultaManagedBean.impuestosSeleccionados}" 
                                    var="impuesto"
                                    editable="false" emptyMessage="#{msj['label.lista.vacia']}"
                                    rowKey="#{impuesto}"
                                    rendered="#{cifrasConsultaManagedBean.cifrasAttributeHelper.tablaImpuestosVisible}">                               
                        	<f:facet name="header">
                           	<h:outputText value="#{msj['titulo.cifras.tabla.impuestos.titulo']}"/>
                           </f:facet>                              
                           <p:column headerText="#{msj['titulo.cifras.tabla.impuestos.impuesto']}" width="18%" >
                           		<h:outputText value="#{impuesto.impuestoConcepto.impuesto.descripcion}"/>
                           </p:column>
                           <p:column headerText="#{msj['titulo.cifras.tabla.impuestos.concepto']}" width="17%" >
                           		<h:outputText value="#{impuesto.impuestoConcepto.concepto.descripcion}"/>
                           </p:column>
                           <p:column headerText="#{msj['titulo.cifras.tabla.impuestos.antecedente']}" width="13%" >
                           		<h:outputText value="#{impuesto.derivaAntecedente == Constantes.BIG_DECIMAL_CERO ? 'NO' : 'SI'}"/>
                           </p:column>
                           <p:column headerText="#{msj['titulo.cifras.tabla.impuestos.fecha.pago']}" width="10%">
                               <h:outputText value="#{impuesto.fechaPago}">
                               		<f:convertDateTime pattern="dd/MM/yyyy"/>
                               </h:outputText>
                           </p:column>
                           <p:column headerText="#{msj['titulo.cifras.tabla.impuestos.detalle']}" width="12%" >
                           		<p:commandLink value="Detalle" style="color:blue;" action="#{cifrasConsultaManagedBean.mostrarDetalle}" 
                           		process="@this" immediate="true" oncomplete="PF('detalleImpuestoPanelWidget').show();" 
                           			update=":formCifras:detalleImpuestoPanel :formCifras:tablaDocumentosDetalle">
                               		<f:setPropertyActionListener value="#{impuesto}" 
                                        	target="#{cifrasConsultaManagedBean.impuestoSeleccionado}"/>
								</p:commandLink>                                        	 
                           </p:column>
                           <p:column headerText="#{msj['titulo.cifras.tabla.impuestos.total']}" width="20%" styleClass="panel-principal">
                               $<h:outputText value="#{impuesto.total}">
                               		<f:convertNumber pattern="###,###,###,##0.00" locale="es_MX"/>
                               </h:outputText>
                           </p:column> 
                        </p:dataTable>
                        </p:panel>
                </p:column>                                
           	</p:row>
           </p:panelGrid> 
           <p:panelGrid styleClass="noBorders"> 
	           	<p:row>
	           		<p:column>              			        			
	           		</p:column>
	           		<p:column> 
	           			<p:commandButton value="Exportar" ajax="false" disabled="#{cifrasConsultaManagedBean.reporteVisible}">
	           					<p:fileDownload value="#{cifrasConsultaManagedBean.archivoExcel}" />
	           			</p:commandButton>
	           		</p:column>	           		
	           	</p:row>
			</p:panelGrid>
           </p:panel>                    
    </html>
</f:view>